# Generated by Django 3.2.6 on 2021-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ready_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='url',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.DeleteModel(
            name='PersReady',
        ),
    ]
