# Generated by Django 3.2.5 on 2021-07-17 01:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210717_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='123', max_length=128, region=None),
        ),
    ]
